version: '2'
services:
  custportapp-postgresql:
    image: postgres:12.1
    volumes:
      - ./postgresql-db:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=custportApp
      - POSTGRES_PASSWORD=
    ports:
      - 5432:5432
