version: '2'
services:
  custportapp-postgresql:
    image: postgres:12.1
    # volumes:
    #     - ~/volumes/jhipster/custportApp/postgresql/:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=custportApp
      - POSTGRES_PASSWORD=
    ports:
      - 5432:5432
